/**
 * Shared invariants for the four "words" scaffolds:
 * stories, quizzes, websites, characters.
 * No network, no real OS paths, no keychain. Pure in-memory checks.
 */

import { describe, expect, it } from 'vitest';
import type { ScaffoldDef } from '../src/types.js';
import { storiesScaffold } from '../src/projects/scaffolds/stories.js';
import { quizzesScaffold } from '../src/projects/scaffolds/quizzes.js';
import { websitesScaffold } from '../src/projects/scaffolds/websites.js';
import { charactersScaffold } from '../src/projects/scaffolds/characters.js';

const SCAFFOLDS: ScaffoldDef[] = [
  storiesScaffold,
  quizzesScaffold,
  websitesScaffold,
  charactersScaffold,
];

const KID_FILES = ['index.html', 'style.css', 'game.js'];
const ALL_FILES = [...KID_FILES, 'TERMI.md'];
const PRETTY = 'Max & "Rex" <Quest>';

/** Em-dash, en-dash, figure dash, horizontal bar, minus sign. */
const BAD_DASHES = /[‐‑‒–—―−]/;

const NETWORK_TOKENS = [
  'http://',
  'https://',
  'fetch(',
  'XMLHttpRequest',
  'WebSocket',
  'EventSource',
  'sendBeacon',
  'RTCPeerConnection',
  'importScripts',
  'document.cookie',
  'javascript:',
];

describe.each(SCAFFOLDS.map((s) => [s.id, s] as const))('scaffold %s', (_id, scaffold) => {
  it('has a complete definition', () => {
    expect(scaffold.id.length).toBeGreaterThan(0);
    expect(scaffold.label.length).toBeGreaterThan(0);
    expect(scaffold.emoji.length).toBeGreaterThan(0);
    expect(scaffold.ageNote.length).toBeGreaterThan(0);
    expect(scaffold.themes).toHaveLength(2);
  });

  it('has well-formed themes', () => {
    for (const theme of scaffold.themes) {
      expect(theme.id).toMatch(/^[a-z0-9-]+$/);
      expect(theme.label.length).toBeGreaterThan(0);
      expect(theme.emoji.length).toBeGreaterThan(0);
      expect(theme.palette.bg).toMatch(/^#[0-9a-f]{6}$/i);
      expect(theme.palette.fg).toMatch(/^#[0-9a-f]{6}$/i);
      expect(theme.palette.accent).toMatch(/^#[0-9a-f]{6}$/i);
      expect(theme.narrativeIntro.length).toBeGreaterThan(0);
      expect(Object.keys(theme.glyphs).length).toBeGreaterThan(0);
      expect(Object.keys(theme.strings).length).toBeGreaterThan(0);
      expect(typeof theme.nonViolent).toBe('boolean');
      expect(typeof theme.nonCompetitive).toBe('boolean');
    }
  });

  describe.each(SCAFFOLDS.find((s) => s.id === _id)!.themes.map((t) => [t.id, t] as const))(
    'theme %s',
    (_themeId, theme) => {
      const files = scaffold.files(theme, PRETTY);

      it('ships exactly 3 kid files plus TERMI.md', () => {
        expect(Object.keys(files).sort()).toEqual([...ALL_FILES].sort());
        const kidFiles = Object.keys(files).filter((f) => f !== 'TERMI.md');
        expect(kidFiles.length).toBeLessThanOrEqual(3);
      });

      it('has non-empty contents under the size cap', () => {
        for (const name of ALL_FILES) {
          const content = files[name] ?? '';
          expect(content.length).toBeGreaterThan(50);
          expect(Buffer.byteLength(content, 'utf8')).toBeLessThan(256 * 1024);
        }
      });

      it('puts a THEME const block in game.js', () => {
        expect(files['game.js']).toContain('const THEME = {');
        expect(files['game.js']).toContain(`"id": ${JSON.stringify(theme.id)}`);
      });

      it('contains no dash characters anywhere', () => {
        for (const content of Object.values(files)) {
          expect(content).not.toMatch(BAD_DASHES);
        }
      });

      it('makes no network or unsafe calls', () => {
        for (const content of Object.values(files)) {
          for (const token of NETWORK_TOKENS) {
            expect(content).not.toContain(token);
          }
        }
        expect(files['game.js']).not.toMatch(/\beval\s*\(/);
        expect(files['game.js']).not.toMatch(/new\s+Function\s*\(/);
      });

      it('builds a CSP-friendly index.html', () => {
        const html = files['index.html'] ?? '';
        expect(html).toContain('<!DOCTYPE html>');
        expect(html).toContain('<link rel="stylesheet" href="style.css">');
        expect(html).toContain('<script src="game.js" defer></script>');
        // No inline handlers: blocked by the preview server CSP.
        expect(html).not.toMatch(/\son[a-z]+="/i);
        expect(html).not.toContain('<script>');
      });

      it('escapes the pretty name in the page', () => {
        const html = files['index.html'] ?? '';
        expect(html).toContain('Max &amp; &quot;Rex&quot; &lt;Quest&gt;');
        expect(html).not.toContain('<Quest>');
      });

      it('produces syntactically valid game.js', () => {
        const js = files['game.js'] ?? '';
        // Compile-only syntax check on our own template output.
        // The function is never invoked and the input is first-party,
        // generated by this repo's scaffold code, not user data.
        expect(() => new Function(js)).not.toThrow();
      });

      it('offers 5 kid-voiced starter prompts', () => {
        const prompts = scaffold.starterPrompts(theme);
        expect(prompts).toHaveLength(5);
        for (const prompt of prompts) {
          expect(prompt.trim().length).toBeGreaterThan(8);
          expect(prompt.length).toBeLessThanOrEqual(100);
          expect(prompt).not.toMatch(BAD_DASHES);
        }
      });

      it('is deterministic for the same inputs', () => {
        const again = scaffold.files(theme, PRETTY);
        expect(again).toEqual(files);
      });
    },
  );
});

describe('kid-facing text rules', () => {
  it('keeps ageNote and intros free of dashes', () => {
    for (const scaffold of SCAFFOLDS) {
      expect(scaffold.ageNote).not.toMatch(BAD_DASHES);
      expect(scaffold.label).not.toMatch(BAD_DASHES);
      for (const theme of scaffold.themes) {
        expect(theme.narrativeIntro).not.toMatch(BAD_DASHES);
        expect(theme.label).not.toMatch(BAD_DASHES);
        for (const value of Object.values(theme.strings)) {
          expect(value).not.toMatch(BAD_DASHES);
        }
      }
    }
  });

  it('declares no vendor files (plain templates only)', () => {
    for (const scaffold of SCAFFOLDS) {
      expect(scaffold.vendorFiles).toBeUndefined();
    }
  });
});
